### ISSUE TITLE
Definir los labels para agrupar funcionalidad

### ISSUE THREAD

**Issue by hanoii** [hanoii/tallerproyectos2#1]
@riseba @DamnMusz 

Tenemos que definir los labels que van a ser los main topics del issue.

En este primer post mantengo la lista actualizada:

Para empezar podrían ser:
- Backend
- Productos
- Clientes
- Agenda
- QR
- Mapa

Los labels se pueden confirmar.

**Comment by riseba** [comment]
Me parece bien. Comenzaría definiendo al menos los que necesitamos para la próxima entrega.
Yo empezaría definiendo Clientes, Productos y Pedidos.
Agenda que sería? no es medio parecido a clientes?

**Comment by hanoii** [comment]
En realidad hay que hacer todo el backlog, así que hay que pensar en todos los labels.

Pueden surgir más a medida que avancemos.

**Comment by riseba** [comment]
Cierto, como hacemos? Empezamos a tirar así nomas como se nos van ocurriendo? y que los demas comenten?

**Comment by hanoii** [comment]
Y para arrancar te diría que si
