### ISSUE TITLE
Armar Pedido

### ISSUE THREAD

**Issue by riseba** [hanoii/tallerproyectos2#11]
Armar un pedido agregando productos del catálogo.

Criterios de aprobación:

1. El botón más y menos deberá incrementar/decrementar de a 1 cuando se apreta una vez, o con velocidad variable en aumento cuando se deja apretado.
1. El switch de "Solo pedido" mostrará todos los productos o solo los que tienen cantidad >0.
1. Al confirmar el pedido, éste será enviado inmediatamente, dando error si no hay conectividad.

**Comment by MatSebMan** [comment]
Convertido en #84
