### ISSUE TITLE
Pantalla de pedido inicial

### ISSUE THREAD

**Issue by hanoii** [hanoii/tallerproyectos2#50]
Propuesta de un mockup para la pantalla del pedido para la segunda entrega.

A esta pantalla de accede desde un botón "Generar pedido" cuando se ve al detalle del cliente.

La idea es obtener el pedido con la menor cantidad de clicks/taps posibles.

![file 4-7-16 20 38 38](https://cloud.githubusercontent.com/assets/677879/14370229/8c4b98c6-fd02-11e5-9341-71a09913283c.jpeg)

Cosas a tener en cuenta:

- El switch "solo pedidos" mostrará todos los productos filtrados o solo los que ya tienen cantidad en el epdido
- Los botones mas y menos agregarán una unidad con un solo tap, o si se los deja apretados, irán agregando de a 1 cada vez más rápido..
- Recomenzar saca todas las cantidades
- Confirmar guarda/envía el pedido.
- El campo buscar en principio solo en nombre.
- Haciendo click en la línea del producto, se accede al detalle del mismo.

**Comment by alemolinari** [comment]
Está bueno, me gusta!
¿Qué pasó con el proto.io?
Por cada item se podría agregar un subtotal?
estilo esta: https://goo.gl/9xwZc2
Les dejo una inquietud: con el tema de las categorías para la búsqueda/filtros, cómo hacemos? idem con las marcas...
¿Por qué está sólo Ariel participando en el github de esta pantalla?

**Comment by hanoii** [comment]
Lo charlamos todos en slack y yo lo puse acá para validarlo.

El subtotal se podría agregar perfectamente.

El tema de filtro por marcas y categorías, yo lo dejaría para la tercera entrega, pero haciendo que el campo de búsqueda también sirva para marca y categoría. Creo que se podrían agregar al menu lateral.

El proto.io está buenísimo, pero lleva mucho tiempo para plasmar una idea que encima puede cambiar bastante, optamos por el papel por ahora.
