### ISSUE TITLE
Lista de Todos los Clientes

### ISSUE THREAD

**Issue by riseba** [hanoii/tallerproyectos2#9]
Lista con todos los clientes del vendedor.

**Comment by riseba** [comment]
Muestra una lista con todos los clientes.
En cada item de la lista se ve:

Icono del cliente con imagen a definir
Nombre y Apellido completo de Cliente (o Razón social)
Dirección del cliente (Solo Argentina)

Al tocar cualquiera de los items abre los detalles

**Comment by MatSebMan** [comment]
Creada la vista de cliente
